### ISSUE TITLE
composite the tiles

### ISSUE THREAD

**Issue by mdsumner** [MilesMcBain/slippymath#1]
I've put the readme `images` onto the tile_grid list. 

I ignore the zoom, and simply apply the tile's x, y as the extent (+1 for x,  but max - (y+1) for y).  That needs the reverse scaling done in `latlon_to_tilenum` but applied as Mercator - I've got this somewhere ...

```R
tile_grid$images <-
  pmap_chr(tile_grid$tiles,
       function(x, y, zoom){
         outfile <- paste0(x, "_", y, "_", ".jpg")
         if (!file.exists(outfile)) curl_download(url = glue(mapbox_query_string),
                       destfile = outfile)
         outfile 
       }, zoom = zoom)


br <- lapply(tile_grid$images, brick)
for (i in seq_along(br)) {
  extent(br[[i]]) <- extent(c(tile_grid$tiles$x[i], tile_grid$tiles$x[i] + 1),
                            ## y goes down
                            max(tile_grid$tiles$y) - c(tile_grid$tiles$y[i] + 1, tile_grid$tiles$y[i]))
}

im <- purrr::reduce(br, raster::merge)
plotRGB(im)

```

NOTE: this image is completely ungeoreferenced!  It needs scaling based on the zoom level and the relation between tile and Mercator. 

![image](https://user-images.githubusercontent.com/4107631/48069160-d1ba0b00-e228-11e8-8805-50ec3383e6a4.png)

**Comment by mdsumner** [comment]
Suggestions: 

* store the zoom and the image type in the file name and whatever else, so they are unique and identifiable out of context
* keep tables of tiles, use them to do tile-math to get extent, then all you need is  `tiles[c("xmin", "xmax", "ymin", "ymax", "nrow", "ncol")]` in order to construct a raster 


RGB bricks complicate things a little, but these strictly never overlap so there shouldn't any problem always using 3-layers (we could use a palette, but I doubt that's worthwhile). 

Possibly the PNG format (rather than JPEG) will already be palettized (JPEG can't do it).

**Comment by MilesMcBain** [comment]
Beautiful! 😍

**Comment by mdsumner** [comment]
This tile logic will tie in very well to an interactive viewer, you won't need to merge with raster just stream them into the screen on the VR wall :)

**Comment by MilesMcBain** [comment]
I can see that working, but for my workflow I need the image to be spatially referenced so I can potentially crop, and calculate the texture coordinates for a spatially referenced mesh.

**Comment by mdsumner** [comment]
Have to retrace through the reverse logic, the Mercator extent is listed here

https://github.com/mapbox/sphericalmercator/blob/master/sphericalmercator.js

where MAXEXTENT is the bounds between [-180, 180] and [-85.0511, 85.0511]

https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Tile_numbers_to_lon..2Flat.

I expect you'll figure it out before I have my second coffee

**Comment by MilesMcBain** [comment]
Wow I hate that JS code. Copy-pasta magic number mess.

**Comment by MilesMcBain** [comment]
I think the strat I am going to go with is calculate the box corners in lat long and reproject those to web mercator. In a similar to vein to this bash + AWK example: https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Tile_bounding_box_and_center

That ends up with a lat lon bbox, I think I could reproject that and things might work.

**Comment by mdsumner** [comment]
It will but def need the arithmetic in native Mercator so individual tiles are trivially georeferenced from tilenum and zoom - I'll get it eventually :)

**Comment by mdsumner** [comment]
Oh I think I got it, tile numbers are zero-based 


```R
tsize <- 256
z0_size <- ((MAXEXTENT * 2)/tsize)
xlim <- -MAXEXTENT + (range(tile_grid$tiles$x) + c(0, 1)) * (z0_size/(2^zoom)) * tsize
ylim <- range(MAXEXTENT - (range(tile_grid$tiles$y) + c(0, 1) - 0) * (z0_size/(2^zoom))*tsize)

```

**Comment by MilesMcBain** [comment]
Ah okay, so for a given tile size you just spread them evenly along the extent?

**Comment by mdsumner** [comment]
Yes, it's a bit funny there using every tile x, but we are targetting the extent of the merged raster not each one. Because tiles x and y are 0 based, their *range* needs an added c(0, 1) to make it an interval to the edge of the last tile. Here's an example (I added an output directory, and zoom in the file name - assuming cleanup each time). 

```R

library(sf)     ## st_bbox, st_crs
library(purrr) ## is_null
library(slippymath)
uluru_bbox <-
  st_bbox(c(xmin = 130,
            xmax = 146,
            ymin = -36,
            ymax = -28),
          crs = st_crs("+proj=longlat +ellps=WGS84"))

bb_tile_query(uluru_bbox)


bb_to_tg(uluru_bbox, max_tiles = 16)
library(purrr)
library(curl)
library(glue)
library(raster)
tile_grid <- bb_to_tg(uluru_bbox, max_tiles = 16)
zoom <- tile_grid$zoom

mapbox_query_string <-
  paste0("https://api.mapbox.com/v4/mapbox.satellite/{zoom}/{x}/{y}.jpg90",
         "?access_token=",
         Sys.getenv("MAPBOX_API_KEY"))

dir.create("outdir")
tile_grid$images <-
  pmap_chr(tile_grid$tiles,
           function(x, y, zoom){
             outfile <- file.path("outdir", paste0(x, "_", y, "_", zoom, "_", ".jpg"))
             if (!file.exists(outfile)) curl_download(url = glue(mapbox_query_string),
                                                      destfile = outfile)
             outfile
           }, zoom = zoom)


br <- lapply(tile_grid$images, brick)
for (i in seq_along(br)) {
  extent(br[[i]]) <- extent(c(tile_grid$tiles$x[i], tile_grid$tiles$x[i] + 1),
                            ## y goes down
                            #max(tile_grid$tiles$y) - c(tile_grid$tiles$y[i] + 1, tile_grid$tiles$y[i]))
                            -c(tile_grid$tiles$y[i] + 1, tile_grid$tiles$y[i]))
}

im <- purrr::reduce(br, raster::merge)
plotRGB(im)



#MAXEXTENT is the bounds between [-180, 180] and [-85.0511, 85.0511]
MAXEXTENT <- 20037508.342789244;
A <- 6378137.0
st_transform(st_as_sfc(uluru_bbox), glue("+proj=merc +a={A} +b={A}"))

tsize <- 256
z0_size <- ((MAXEXTENT * 2)/tsize)
xlim <- -MAXEXTENT + (range(tile_grid$tiles$x) + c(0, 1)) * (z0_size/(2^zoom)) * tsize
ylim <- range(MAXEXTENT - (range(tile_grid$tiles$y) + c(0, 1) - 0) * (z0_size/(2^zoom))*tsize)

range_buff <- function(x, buf = 0.1) {
  x + c(-1, 1) * buf
}
xy <- maps::map(plot = FALSE)
xy <- rgdal::project(cbind(xy$x, xy$y), glue("+proj=merc +a={A} +b={A}"))
plot(extent(xlim, ylim), xlim = range_buff(xlim), ylim = range_buff(ylim), asp = 1)
plotRGB(setExtent(im, extent(xlim, ylim)), add = TRUE)
points(xy)
abline(v = xlim, h = ylim)
## notice that our input window won't match our output, because tiles are chosen by intersection
plot(st_transform(st_as_sfc(uluru_bbox), glue("+proj=merc +a={A} +b={A}")), add = TRUE, lwd = 4, lty = 2)
```

![image](https://user-images.githubusercontent.com/4107631/48102049-4cad1100-e27d-11e8-9b43-8f36d009f242.png)



Testing on other data sets and so far so good

![image](https://user-images.githubusercontent.com/4107631/48102032-3f902200-e27d-11e8-8684-c90780f4ce00.png)

I haven't had that second coffee yet, otherwise I'd clean up my trail a bit more. Later today!  This is exciting, fantastic to finally have total control over the tiles - great work!

**Comment by MilesMcBain** [comment]
This is so great to see thanks Mike!

So `MAXEXTENT` is `A * pi` as per the comment on this page: https://epsg.io/3857 is that where it came from?

**Comment by mdsumner** [comment]
Yeah, the distance from the prime meridian to the anti meridian, 0 to 180 along the equator

**Comment by mdsumner** [comment]
I'm keen to expand on explanations here, I'm not totally au fait with everything but have some well worn understandings, really wish this was better understood by many - and I'm excited that we can easily explain it with this package!

**Comment by mdsumner** [comment]
I consider this done, a very good outcome all round. My version of the georef logic is in [ceramic](https://github.com/hypertidy/ceramic)
