### ISSUE TITLE
CRAN plans

### ISSUE THREAD

**Issue by 16EAGLE** [MilesMcBain/slippymath#10]
Thanks for this useful package. I am using it for the retrieval of default base maps in [`moveVis`](https://github.com/16eagle/movevis) in case custom raster imagery is not provided by the user.

Do you plan to submit `slippymath` to CRAN and if so, do you already know when you would do that? I would very much like to use `slippymath` as a dependency to `moveVis`.

**Comment by MilesMcBain** [comment]
Thanks for your interest @16EAGLE. I am planning on submitting to CRAN very soon. These are the 3 things I want to do before that happens:

- [x] Small vignette specifically about fetching elevation data from Mapbox.
- [x] Deal with the `rgdal` dependency properly, by checking it is present. OR remove rgdal altogether.
- [x] Review all function names

Re the last point, do you have any feedback about the function names? I was writing a lot of `sf` when I made this package but coming back to it after a short break I find things like `bb_to_tg` to be a bit too terse. Maybe `bbox_to_tilegrid` or similar would be better? 

Edit: I am aiming to have these resolved within the next 1 - 2 weeks.

**Comment by 16EAGLE** [comment]
Great, I am looking forward to read the finished vignette. Regarding the function names, I personally like short and abbreviated names. However, a name like `bbox_to_tilegrid` is more self-explanatory, which is why I would probably prefer it over `bb_to_gg`. Also, `bbox_to_tilegrid` seems to be more in line with some other function names in `slippymath`, e.g. `latlon_to_tilenum` or `raster_to_png`.

**Comment by MilesMcBain** [comment]
Hi @16EAGLE, I am pretty close now and have implemented a few breaking function name changes along the lines mentioned above. They're covered in NEWS.md.

**Comment by 16EAGLE** [comment]
Thanks for notifying, I updated the names of the `slippymath` functions used by `moveVis`.

**Comment by MilesMcBain** [comment]
A heads up: After a lengthly stay in the queue `slippymath` was rejected yesterday for lack of executable examples in the help files. I'm onto that now.

**Comment by 16EAGLE** [comment]
Good luck for the next submission!

**Comment by MilesMcBain** [comment]
I've just heard `slippymath` is on its way to CRAN. 🎉 Cc @mdsumner
