### ISSUE TITLE
Calculate tile_bb without sf, drop sf dependency.

### ISSUE THREAD

**Issue by MilesMcBain** [MilesMcBain/slippymath#4]
If `tile_bb` could avoid using `sf` the whole dependency could be dropped and make this package more attractive for developers.

I plan to make this change after some pressing matters, in December 2018 before submitting this to CRAN.

**Comment by mdsumner** [comment]
fwiw I've been experimenting with that https://github.com/hypertidy/ceramic/blob/master/R/locale.R#L89-L91

My interface is "long-lat" pair plus a buffer in kilometres, that fits how I like to think about this.

**Comment by MilesMcBain** [comment]
Done.
